function toNumber(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function parseTimeMs(iso) {
  const ms = Date.parse(String(iso || ""));
  return Number.isFinite(ms) ? ms : null;
}

function sortCandidates(a, b) {
  const sa = toNumber(a?.score) ?? -999;
  const sb = toNumber(b?.score) ?? -999;
  if (sb !== sa) return sb - sa;

  const ta = parseTimeMs(a?.publishedAt) ?? parseTimeMs(a?.updatedAt) ?? 0;
  const tb = parseTimeMs(b?.publishedAt) ?? parseTimeMs(b?.updatedAt) ?? 0;
  if (tb !== ta) return tb - ta;

  return String(a?.title || "").localeCompare(String(b?.title || ""));
}

function buildDedupGroupIndex(ingested) {
  const groups = Array.isArray(ingested?.dedup?.groups) ? ingested.dedup.groups : [];
  const map = new Map();
  for (const g of groups) {
    const key = String(g?.key || "");
    if (!key) continue;
    map.set(key, g);
  }
  return map;
}

function enrichWithDedupGroup(item, groupIndex) {
  const key = String(item?.dedup?.key || "");
  if (!key || !groupIndex.has(key)) return item;
  const g = groupIndex.get(key);
  return {
    ...item,
    dedupGroup: {
      key: g.key,
      basis: g.basis,
      memberCount: g.memberCount,
      sources: g.sources || []
    }
  };
}

module.exports = (() => {
  // This file is generated by `npm run ingest`; keep the candidates view resilient when absent.
  let ingested = null;
  try {
    // eslint-disable-next-line global-require, import/no-unresolved
    ingested = require("./ingested.json");
  } catch (e) {
    return { available: false, items: [], totalItems: 0, topCount: 0 };
  }

  const items = Array.isArray(ingested?.items) ? ingested.items : [];
  const groupIndex = buildDedupGroupIndex(ingested);

  const canonicalOnly = items.filter((it) => {
    if (!it || !it.dedup) return true;
    return Boolean(it?.dedup?.isCanonical);
  });

  // Prefer canonical items, but fall back to raw ingested items if dedup output is sparse/missing.
  const baseItems = canonicalOnly.length ? canonicalOnly : items;

  const enriched = baseItems.map((it) => enrichWithDedupGroup(it, groupIndex));
  const sorted = [...enriched].sort(sortCandidates);
  const top = sorted.slice(0, 50);

  return {
    available: true,
    generatedAt: ingested?.generatedAt || null,
    run: ingested?.run || null,
    scoring: ingested?.scoring || null,
    classification: ingested?.classification || null,
    dedup: ingested?.dedup || null,
    totalItems: items.length,
    uniqueItems: canonicalOnly.length || items.length,
    topCount: top.length,
    items: top
  };
})();
