function toNumber(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function parseTimeMs(iso) {
  const ms = Date.parse(String(iso || ""));
  return Number.isFinite(ms) ? ms : null;
}

function sortCandidates(a, b) {
  const sa = toNumber(a?.score) ?? -999;
  const sb = toNumber(b?.score) ?? -999;
  if (sb !== sa) return sb - sa;

  const ta = parseTimeMs(a?.publishedAt) ?? parseTimeMs(a?.updatedAt) ?? 0;
  const tb = parseTimeMs(b?.publishedAt) ?? parseTimeMs(b?.updatedAt) ?? 0;
  if (tb !== ta) return tb - ta;

  return String(a?.title || "").localeCompare(String(b?.title || ""));
}

module.exports = (() => {
  // This file is generated by `npm run ingest`; keep the candidates view resilient when absent.
  let ingested = null;
  try {
    // eslint-disable-next-line global-require, import/no-unresolved
    ingested = require("./ingested.json");
  } catch (e) {
    return { available: false, items: [], totalItems: 0, topCount: 0 };
  }

  const items = Array.isArray(ingested?.items) ? ingested.items : [];
  const sorted = [...items].sort(sortCandidates);
  const top = sorted.slice(0, 50);

  return {
    available: true,
    generatedAt: ingested?.generatedAt || null,
    run: ingested?.run || null,
    scoring: ingested?.scoring || null,
    totalItems: items.length,
    topCount: top.length,
    items: top
  };
})();

